FROM lwolf/golang-glide:0.12.3

ENV APP_PATH=/go/src/github.com/zanetworker/son-selfservice/selfservice-backend
ENV CGO_ENABLED 0
ENV GOOS "linux"
ENV GOARCH "amd64"

RUN mkdir -p $APP_PATH
WORKDIR $APP_PATH

COPY glide.yaml glide.yaml
COPY glide.lock glide.lock
RUN glide install -v

RUN echo $GOPATH
VOLUME ["/build"]
ADD . $APP_PATH
# CMD GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /build/selfservice-backend
EXPOSE 4000
